const ADD_ADMIN = "ADD_ADMIN";
const GET_ADMIN = "GET_ADMIN";
const UPDATE_ADMIN = "UPDATE_ADMIN";
const REMOVE_ADMIN = "REMOVE_ADMIN";

export {
    ADD_ADMIN,
    GET_ADMIN,
    UPDATE_ADMIN,
    REMOVE_ADMIN
}
